service: note-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - NoteTable
          - Arn

resources:
  Resources:
    NoteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NoteTable
        KeySchema:
          - AttributeName: userEmail
            KeyType: HASH
          - AttributeName: noteDate
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: userEmail
            AttributeType: S
          - AttributeName: noteDate
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  addNote:
    handler: functions/addNote.handler
    events:
      - http:
          method: post
          path: /note
  deleteNote:
    handler: functions/deleteNote.handler
    events:
      - http:
          path: /note/{noteDate}
          method: delete
  getAllNotes:
    handler: functions/getAllNotes.handler
    events:
      - http:
          path: /note
          method: get
  registerUser:
    handler: functions/register.handler
    events:
      - http:
          method: post
          path: /register
  loginUser:
    handler: functions/login.handler
    events:
      - http:
          method: post
          path: /login
