service: note-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - NoteTable
          - Arn
    - Effect: Allow
      Action:
        - cognito-idp:AdminConfirmSignUp
      Resource:
        - !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}
  environment:
    COGNITO_CLIENT_ID:
      Ref: CognitoUserPoolClient
    COGNITO_USER_POOL_ID:
      Ref: CognitoUserPool

resources:
  Resources:
    NoteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NoteTable
        KeySchema:
          - AttributeName: userEmail
            KeyType: HASH
          - AttributeName: noteDate
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: userEmail
            AttributeType: S
          - AttributeName: noteDate
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: noteAppUserPool
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: noteAppUserPoolClient
        GenerateSecret: false
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - USER_PASSWORD_AUTH

functions:
  addNote:
    handler: functions/addNote.handler
    events:
      - http:
          method: post
          path: /note
  deleteNote:
    handler: functions/deleteNote.handler
    events:
      - http:
          path: /note/{noteDate}
          method: delete
  getAllNotes:
    handler: functions/getAllNotes.handler
    events:
      - http:
          path: /note
          method: get
  registerUser:
    handler: functions/register.handler
    events:
      - http:
          method: post
          path: /register
  loginUser:
    handler: functions/login.handler
    events:
      - http:
          method: post
          path: /login
